apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-keyvault-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:                                  
    - secretName: api-keys
      type: Opaque
      data:
        - objectName: OPENWEATHER-API-KEY         
          key: openweatherApiKey
        - objectName: OPENCAGE-API-KEY           
          key: opencageApiKey
  parameters:
    usePodIdentity: "false"
    userAssignedIdentityID: "enter_client_id"     # Enter client (app) id
    keyvaultName: "myKeyVault-l2ol3tonyesic"
    objects: |
      array:
        - |
          objectName: OPENWEATHER-API-KEY        # The secret name must match exactly
          objectType: secret                     # The object type should be 'secret'
        - |
          objectName: OPENCAGE-API-KEY          
          objectType: secret                     
    tenantId: "enter_tenant_id"                 # Enter tenant right              

